##############################################################
##############################################################
# This is an example configuration provided by Wraith.
# Feel free to amend for your own requirements.
# ---
# This particular config is intended to demonstrate how
# to use Wraith in 'capture' mode, which is best suited to
# comparing a test and live version of the same website.
#
# `wraith capture capture.yaml`
#
##############################################################
##############################################################

# (required) The engine to run Wraith with. Examples: 'phantomjs', 'casperjs', 'slimerjs'
browser: "phantomjs"

# (required) The domains to take screenshots of.
domains:
  current:  "http://www.standardpro.com"
  new:      "http://standardpro.staging.wpengine.com"

# (required) The paths to capture. All paths should exist for both of the domains specified above.
paths:
  home-en: /
  home-fr: /fr/
  about-us-en: /about-us/
  executive-team-en: /about-us/executive-team/
  our-corporate-values-en: /about-us/our-corporate-values/
  a-propos-de-standard-fr: /fr/a-propos-de-standard/
  histoire-de-standard-fr: /fr/a-propos-de-standard/histoire-de-standard/
  prix-et-engagements-sociaux-fr: /fr/a-propos-de-standard/prix-et-engagements-sociaux/
  careers-en: /careers/
  carrieres-fr: /fr/carrieres/
  contact-us-en: /contact-us/
  nous-joindre-fr: /fr/nous-joindre/
  e-catalog-en: /e-catalog/
  e-catalog-fr: /fr/e-catalog/
  tools-en: /tools/
  documentation-en: /tools/documentation/
  certifications-en: /tools/certifications/
  photometry-tool-en: /tools/photometry-tool/
  outils-fr: /fr/outils/
  calculateur-leed-fr: /fr/outils/calculateur-leed/
  documentation-fr: /fr/outils/documentation/
  outil-photometrie-fr: /fr/outils/outil-photometrie/
  services-publics-fr: /fr/outils/services-publics/
  colour-temperature-en: /colour-temperature/
  Temperature-de-couleur-fr: /fr/temperature-de-couleur/
  our-services-en: /our-services/
  energy-saving-request-en: /our-services/energy-saving-request/
  project-department-en: /our-services/project-department/
  nos-services-fr: /fr/nos-services/
  demande-pour-une-estimation-de-couts-fr: /fr/nos-services/demande-pour-une-estimation-de-couts/
  departement-des-projets-fr: /fr/nos-services/departement-des-projets/
  blog-en: /blog/
  nouvelles-fr: /fr/nouvelles/
  category-corporate-news-en: /category/corporate-news/
  category-our-online-journal-en: /category/our-online-journal/
  category-lighting-aplication-recommandations-en: /category/our-online-journal/lighting-aplication-recommandations/
  category-the-basics-of-lighting-en: /category/our-online-journal/the-basics-of-lighting/
  category-actualites-entreprise-fr: /fr/category/actualites-entreprise/
  category-notre-journal-en-ligne-fr: /fr/category/notre-journal-en-ligne/
  category-les-rudiments-de-leclairage-fr: /fr/category/notre-journal-en-ligne/les-rudiments-de-leclairage/
  category-recommandations-declairage-par-applications-fr: /fr/category/notre-journal-en-ligne/recommandations-declairage-par-applications/
  challenges-and-solutions-for-indoor-pool-lighting-en: /challenges-and-solutions-for-indoor-pool-lighting/
  characteristics-of-lighting-systems-in-parking-en: /characteristics-of-lighting-systems-in-parking/
  lighting-in-hotels-en: /lighting-in-hotels/
  llet-there-be-light-the-advent-of-the-light-bulb-en: /llet-there-be-light-the-advent-of-the-light-bulb/
  understanding-lifi-technology-en: /understanding-lifi-technology/
  3-types-declairage-de-base-2-fr: /fr/3-types-declairage-de-base-2/
  7-categories-despaces-et-leurs-exigences-en-matiere-declairage-fr: /fr/7-categories-despaces-et-leurs-exigences-en-matiere-declairage/
  comprendre-la-difference-de-lumen-des-sources-dhi-vs-del-fr: /fr/comprendre-la-difference-de-lumen-des-sources-dhi-vs-del/
  defis-et-solutions-pour-les-problemes-declairage-des-piscines-interieures-2-fr: /fr/defis-et-solutions-pour-les-problemes-declairage-des-piscines-interieures-2/
  du-del-dans-les-rues-fr: /fr/du-del-dans-les-rues/
  products-en: /products/
  produits-fr: /fr/produits/
  sp_products_cats-downlight-en: /products/downlight/
  sp_products_cats-led-downlights-en: /products/downlight/led-downlights/
  sp_products_cats-led-high-bay-luminaires-en: /products/indoor-luminaires/led-high-bay-luminaires/
  sp_products_cats-led-lamps-en: /products/led-lamps/
  sp_products_cats-design-lamps-en: /products/led-lamps/design-lamps/
  sp_products_cats-luminaires-encastres-traditionnels-fr: /fr/products/encastres/luminaires-encastres-traditionnels/
  sp_products_cats-lampes-del-fr: /fr/products/lampes-del/
  sp_products_cats-lampes-design-fr: /fr/products/lampes-del/lampes-design/
  sp_products_cats-substitut-de-lampes-traditionnelles-fr: /fr/products/lampes-del/substitut-de-lampes-traditionnelles/
  sp_products_cats-lampes-lfc-fr: /fr/products/traditionnels/lampes-lfc/
  led-g9-lamps-en: /featured-product/led-g9-lamps/
  led-gimbal-downlights-en: /featured-product/led-gimbal-downlights/
  led-strip-light-lss-series-en: /featured-product/led-strip-light-lss-series/
  sleek-wall-pack-en: /featured-product/sleek-wall-pack/
  t5ho-high-bay-en: /featured-product/t5ho-high-bay/
  encastre-del-traditionnel-fr: /fr/produit-vedette/encastre-del-traditionnel/
  flexled-solutions-integrees-de-del-encastrees-fr: /fr/produit-vedette/flexled-solutions-integrees-de-del-encastrees/
  lampes-a19-ecoenergetiques-fr: /fr/produit-vedette/lampes-a19-ecoenergetiques/
  luminaire-mural-del-fr: /fr/produit-vedette/luminaire-mural-del/
  plafonnier-del-edge-lit-fr: /fr/produit-vedette/plafonnier-del-edge-lit/
  solutions-en: /solutions/
  solutions-fr: /fr/solutions/
  bathroom-en: /solution/bathroom/
  kitchen-en: /solution/kitchen/
  parking-indoor-outdoor-en: /solution/parking-indoor-outdoor/
  chambre-de-patient-fr: /fr/solution/chambre-de-patient/
  stockage-des-aliments-fr: /fr/solution/stockage-des-aliments/
  toilettes-fr: /fr/solution/toilettes/
  sp_solutions_cats-retail-en: /solutions/commercial/retail/
  sp_solutions_cats-residential-en: /solutions/residential/
  sp_solutions_cats-multi-residential-en: /solutions/residential/multi-residential/
  sp_solutions_cats-restaurants-fr-fr: /fr/solutions/commerciale/restaurants-fr/
  sp_solutions_cats-hopitaux-fr: /fr/solutions/institutionnel/hopitaux/
  sp_solutions_cats-residence-unifamiliale-fr: /fr/solutions/residentiel/residence-unifamiliale/
  sp_success_stories-archive-en: /success-stories/
  sp_success_stories-archive-fr: /fr/succes-dentreprise/
  christmas-lights-town-riverview-en: /success-stories/christmas-lights-town-riverview/
  manoir-lac-brome-en: /success-stories/manoir-lac-brome/
  salon-de-coiffure-espace-k-en: /success-stories/salon-de-coiffure-espace-k/
  eclairage-de-noel-a-riverview-fr: /fr/succes-dentreprise/eclairage-de-noel-a-riverview/
  transit-henri-iv-fr: /fr/succes-dentreprise/transit-henri-iv/
  une-solution-integrale-interieure-et-exterieure-pour-un-immeuble-locatif-fr: /fr/succes-dentreprise/une-solution-integrale-interieure-et-exterieure-pour-un-immeuble-locatif/
  sp_success_story_applications-art-galleries-and-museums-en: /application-types/art-galleries-and-museums/
  sp_success_story_applications-school-institutions-en: /application-types/school-institutions/
  sp_success_story_applications-sports-facilities-en: /application-types/sports-facilities/
  sp_success_story_applications-commerces-et-magasins-fr: /fr/application-types/commerces-et-magasins/
  sp_success_story_applications-complexes-sportif-fr: /fr/application-types/complexes-sportif/
  sp_success_story_applications-institutions-scolaires-fr: /fr/application-types/institutions-scolaires/
  sp_success_story_solutions-solution-budgetaire-fr: /fr/solution-types/solution-budgetaire/
  sp_success_story_solutions-solution-de-lampes-del-fr: /fr/solution-types/solution-de-lampes-del/


# (required) Screen widths (and optional height) to resize the browser to before taking the screenshot.
screen_widths:
  - 320
  - 600x768
  - 768
  - 1280

# (optional) JavaScript file to execute before taking screenshot of every path. Default: nil
before_capture: 'javascript/disable_javascript--phantom.js'

# (required) The directory that your screenshots will be stored in
directory: 'shots'

# (required) Amount of fuzz ImageMagick will use when comparing images. A higher fuzz makes the comparison less strict.
fuzz: '10%'

# (optional) The maximum acceptable level of difference (in %) between two images before Wraith reports a failure. Default: 0
threshold: 5

# (optional) Specify the template (and generated thumbnail sizes) for the gallery output.
gallery:
  template: 'slideshow_template' # Examples: 'basic_template' (default), 'slideshow_template'
  thumb_width:  200
  thumb_height: 200

# (optional) Choose which results are displayed in the gallery, and in what order. Default: alphanumeric
# Options:
#   alphanumeric - all paths (with or without a difference) are shown, sorted by path
#   diffs_first - all paths (with or without a difference) are shown, sorted by difference size (largest first)
#   diffs_only - only paths with a difference are shown, sorted by difference size (largest first)
# Note: different screen widths are always grouped together.
mode: diffs_first
